name: Docker CI
 
on: push
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Tarkista tiedostot
        run: ls -la
 
      - name: Build Docker image
        run: docker build -t myapp .
